Support Webpack 4
messageformat/loader pull request #6
Opened 2018-04-16 22:20 UTC by cletusw

Hack around https://github.com/webpack/webpack/issues/7057

Fixes #5

2018-04-17 15:19 UTC, eemeli requested changes

2018-04-17 15:19 UTC, eemeli commented on example/package.json
> +    "messageformat": "^1.1.1",
This should work fine with messageformat 2.0.0.

2018-04-17 15:19 UTC, eemeli commented on index.js
> +var JavascriptGenerator = require('./example/node_modules/webpack/lib/JavascriptGenerator');
Depending on the dependencies of the example app is not the right thing to do, at all. In fact the example probably should not even be included in the npm-released build. `webpack` should probably be an optional dependency, and some v4 detector be used to determine whether to use the hack or not.

2018-05-29 19:32 UTC, cletusw commented on example/package.json
> +    "postinstall": "cd .. && npm install && npm install --no-save 'file:./example/node_modules/messageformat' 'file:./example/node_modules/webpack'",
Uses symlinks so we get the version specified below instead of just latest necessarily.

2018-05-29 19:33 UTC, cletusw commented on index.js
> +try {
Allows supporting webpack < 4 at the same time.

2018-05-29 19:33 UTC, cletusw commented
@eemeli Updated. Let me know what you think, thanks!

2018-06-01 10:12 UTC, eemeli commented
I'm growing less convinced that we should hack around Webpack like this. The right thing to do would be to actually submit the PR requested in the upstream issue, and then use that API.

On a sidenote, the `postinstall` hackyness is getting a bit silly. It might make sense to finally bite the bullet and set up a multi-package repo for messageformat using Lerna.

@cletusw Btw, could you sign the JS Foundation CLA?

2018-06-01 15:44 UTC, cletusw commented
Signed.

And while I agree that both changes are getting pretty hacky, I'm not in a position right now to do either of the larger changes. I think this change is better than the current state where users are required to know to put "javascript/auto" in their config. Plus, since I've clearly marked off the hacky area, it should be easy to move to an actual published API whenever someone gets around to it.

2018-07-02 19:52 UTC, cletusw commented
@eemeli Any thoughts on getting this out there to unblock?

2018-07-02 20:36 UTC, eemeli commented
Started looking into Webpack for this a bit for a proper fix, but didn't get deep enough to really figure out how it's all put together before I got distracted; I've spent most of my open-source time on [`yaml`](https://eemeli.org/yaml/) lately.

I'd prefer to leave out the hack, and just ask that users include the `type: 'javascript/auto'` in their config for now. It's pretty certain this'll get fixed in Webpack at some point; until then I think we can just deal with it. :/

2018-07-02 20:51 UTC, closed without merging